### ISSUE TITLE
má formatação de data do método transformString em src/utilities/dataUtilities.js

### ISSUE THREAD

**Issue by GustavoMarks** [GustavoMarks/AutoVeitamento#13]
Ao contrário dos outros métodos de formação de data do mesmo objeto exportado, o método transformString não adiciona zeros à esquerda para datas de dias e mês menores que 10, com isso, as strings de datas saídas desse método terão tamanho variado entre 8, 9, e 10, o que pode ocasionar bugs visuais e desalinhamentos

(bug encontrado pelo script de teste unitário para dataUtilities.js)

**Comment by natalia-rios** [comment]
Closes #13
