### ISSUE TITLE
Remover variáveis ambiente do versionamento

### ISSUE THREAD

**Issue by GustavoMarks** [GustavoMarks/AutoVeitamento#5]
Objetivo: tornar projeto mais seguro e escalável

- [x] Excluir arquivo de configuração de varáveis ambiente .env
- [x] Adicionar nome do arquivo da lista do gitignore
- [x] Adicionar arquivo .env.example para indicar as variáveis ambiente utilizadas no projeto

**Comment by natalia-rios** [comment]
Closes #5
