### ISSUE TITLE
Utilizar apenas um arquivo de configuração de pacotes

### ISSUE THREAD

**Issue by GustavoMarks** [GustavoMarks/AutoVeitamento#6]
- [x]  Escolher ou package-lock.json ou yarn.lock para evitar conflitos e remover redundância, e atualizar o arquivo escolhido
- [x]  Adicionar o arquivo removido ao gitignore
- [x]  Especificar no README o uso do yarn (caso escolha somente yarn.lock) ou uso de npm (caso escolha package-lock.json)

**Comment by natalia-rios** [comment]
refatoração do código

**Comment by GustavoMarks** [comment]
Mesmo incluído no gitignore o arquivo package-lock.json continua no repositório (ele vai ser baixado com o git clone, porém as alterações nele não vão ser versionadas; para não ser baixado com o clone, precisaria ter adicionado um commit com o delete do arquivo antes do commit com a adição ao gitignore), como ele ainda ficará presente no projeto o problema persiste. Um solução rápida é excluir o arquivo package-lock.json (na branch refactoring), pela própria interface do github web, adicionando o commit e atualizando o projeto local com git pull.

**Comment by natalia-rios** [comment]
Closes #6
